In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

In [2]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.shape

(7043, 21)

In [7]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [8]:
df.columns = df.columns.str.strip()

In [9]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [10]:
df["TotalCharges"]= pd.to_numeric(df["TotalCharges"], errors = "coerce")

In [11]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [13]:
#  REMOVE MISSING ROWS 
df = df.dropna().copy()

In [14]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [15]:
df["Churn"] = df["Churn"].map({ "No" : 0,
                                "Yes":1})

print(df["Churn"].value_counts())

Churn
0    5163
1    1869
Name: count, dtype: int64

In [19]:
df = df.drop(columns = ["customerID"],axis =1)

KeyError: "['customerID'] not found in axis"

In [20]:
df = pd.get_dummies(df, drop_first =True)

In [21]:
df.isnull().sum().sum()

0

In [26]:
x = df.drop(columns=["Churn"])
y = df["Churn"]

In [27]:
x.shape

(7032, 30)

In [28]:
y.shape

(7032,)

In [29]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x, y , test_size = 0.2 , random_state = 42,
                                                 stratify = y)

In [30]:
x_train

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1413,0,65,94.55,6078.75,True,True,True,True,False,True,...,False,False,False,False,False,True,False,True,False,False
7003,0,26,35.75,1022.50,True,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3355,0,68,90.20,6297.65,False,True,False,True,False,True,...,False,False,False,False,False,True,False,True,False,False
4494,0,3,84.30,235.05,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
3541,0,49,40.65,2070.75,False,True,False,False,True,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3451,1,65,70.95,4555.20,True,True,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
5123,1,15,75.30,1147.45,False,False,False,True,False,False,...,False,False,False,False,False,False,True,True,False,False
4135,0,36,92.90,3379.25,False,True,True,True,False,True,...,False,True,False,True,False,True,True,True,False,False
4249,0,10,65.90,660.05,False,True,True,True,False,False,...,False,False,False,True,True,False,True,False,False,True
1505,1,1,74.70,74.70,True,False,False,True,False,True,...,False,False,False,False,False,False,True,False,True,False

In [31]:
x_test

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
974,0,59,75.95,4542.35,False,True,True,True,False,False,...,False,True,False,True,False,True,True,True,False,False
619,0,7,78.55,522.95,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
4289,0,54,20.10,1079.45,False,False,False,True,False,False,...,True,False,True,False,False,True,False,False,False,True
3721,0,2,20.65,38.70,False,False,False,True,False,False,...,True,False,True,False,False,False,False,False,False,True
4533,0,71,105.15,7555.00,False,True,False,True,False,True,...,False,True,False,True,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4829,0,12,45.00,524.35,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
5176,0,26,45.80,1147.00,False,False,True,False,True,False,...,False,False,False,True,False,False,False,False,False,True
2750,0,3,19.45,69.25,True,False,False,True,False,False,...,True,False,True,False,True,False,True,False,False,True
4432,0,37,40.55,1390.85,True,False,False,False,True,False,...,False,False,False,False,False,True,True,False,False,True
2091,0,50,20.15,970.85,False,False,True,True,False,False,...,True,False,True,False,False,True,False,True,False,False

In [32]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter = 1000)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

/opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [35]:
from sklearn.metrics import accuracy_score

Accuracy = accuracy_score(y_test,y_pred)
Accuracy

0.8009950248756219

In [37]:
from sklearn.metrics import f1_score, recall_score, precision_score

pre = precision_score(y_test,y_pred)
rec = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [38]:
pre , rec , f1

(0.6424242424242425, 0.5668449197860963, 0.6022727272727273)

In [44]:
metrics = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "Score": [Accuracy, pre, rec, f1]
})

In [45]:
metrics

      Metric     Score
0   Accuracy  0.800995
1  Precision  0.642424
2     Recall  0.566845
3   F1 Score  0.602273

In [ ]:
plt.figure(figsize=(9, 6))

sns.boplot(
    data=metrics,
    x="Metric",
    y="Score",
    hue="Metric",
    palette="viridis",
    legend=False
)

plt.ylim(0, 1)
plt.title("Model Performance Metrics")
plt.xlabel("Metrics")
plt.ylabel("Score")

# Add values on top of bars
for i, value in enumerate(metrics["Score"]):
    plt.text(
        i,
        value + 0.02,
        f"{value:.2f}",
        ha="center",
        fontweight="bold"
    )

plt.show()